### ISSUE TITLE
No `Vary: Origin`

### ISSUE THREAD

**Issue by obscaenvs** [larskuhtz/wai-cors#1]
I have set `corsVaryOrigin` to `True`, as below, but I get no `Vary: Origin` in the response from the server. Fix for now for me is to set this header using WAI middleware.

```
corsPolicy :: CorsResourcePolicy
corsPolicy = CorsResourcePolicy
                    {
                      corsOrigins = Just (["http://example.com"], False)
                    , corsMethods = ["POST"]
                    , corsRequestHeaders = []
                    , corsExposedHeaders = Nothing
                    , corsMaxAge = Nothing
                    , corsVaryOrigin = True
                    , corsRequireOrigin = True
                    , corsIgnoreFailures = False
                    }
```

**Comment by larskuhtz** [comment]
Thanks for the bug report and my apologies that it took me so long to reply to it. The issue got fixed in PR #2. It will be included in version 0.2.4 which I am planning to release soon.
