### ISSUE TITLE
corsOrigins creates invalid Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by alexanderkjeldaas** [larskuhtz/wai-cors#20]
Chrome says:

`The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.`

If corsOrigins is set, then there will typically be two values for this header.  And Chrome barfs and CORS doesn't work.

**Comment by larskuhtz** [comment]
This seems to be a consequence of using two CORS implementations at the same time, as described in #21. If this is not the case, feel free to reopen the issue.
