### ISSUE TITLE
Two Access-Control-Allow-Origin are created when overlaid on servant

### ISSUE THREAD

**Issue by alexanderkjeldaas** [larskuhtz/wai-cors#21]
Servant seems to by default populate Access-Control-Allow-Origin: *.

Adding an additional header can never be correct as it implies two values, which Chrome at least will bafr on.

**Comment by larskuhtz** [comment]
I think, this is an issue of using two different frameworks that both implement CORS. Just pick one or the other, but not both at the same time.
