### ISSUE TITLE
Unclear documentation for `corsIgnoreFailures`

### ISSUE THREAD

**Issue by exarkun** [larskuhtz/wai-cors#30]
[The documentation](https://github.com/larskuhtz/wai-cors/blob/89fde0f64fd2e32636277cb43388433d04962546/src/Network/Wai/Middleware/Cors.hs#L186) says

> Note: Your application needs to will receive preflight OPTIONS requests if set to 'True'.

What does it mean to "needs to will receive"?  I guess this is meant to be either "needs to" or "will".  "will" makes a bit more sense to me, if that's really what the behavior is.

**Comment by larskuhtz** [comment]
Fixed in master. Thanks for reporting!
